version: '3.8'

services:
    db:
        image: 'postgres:12'
        environment:
          - POSTGRES_DB=ddguildirrrde7
          - POSTGRES_USER=ytonraiqrvxqth
          - POSTGRES_PASSWORD=7455eba431309c149474d360a542f486580b64fd7967ef00cb262efc018aa1ea
        ports:
          - '5432:5432'